sentry:
    dsn: '%env(SENTRY_DSN)%'
    messenger:
        enabled: true # flushes Sentry messages at the end of each message handling
        capture_soft_fails: true # captures exceptions marked for retry too
    options:
        environment: '%kernel.environment%'
        sample_rate: 1
        traces_sample_rate: 0.3
    tracing:
        enabled: true
        dbal:
            enabled: true
        cache:
            enabled: true
        twig:
            enabled: true
